"""foundations

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 09:25:13.990147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from procrastinate.schema import SchemaManager
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # Procrastinate job queue lives in the same database (FR-JOB-01).
    op.execute(SchemaManager.get_schema())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index('ix_audit_entity', 'audit_event', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_org_at', 'audit_event', ['organisation_id', 'at'], unique=False)
    op.create_table('idempotency_record',
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('subject', 'key', name=op.f('pk_idempotency_record'))
    )
    op.create_table('organisation',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('default_timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation')),
    sa.UniqueConstraint('slug', name=op.f('uq_organisation_slug'))
    )
    op.create_table('rate_bucket',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tokens', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('refill_per_second', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_rate_bucket'))
    )
    op.create_table('organisation_user',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_organisation_user_organisation_id_organisation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_organisation_user'))
    )
    op.create_table('site',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_scheme', sa.String(length=40), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('covers', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_site_organisation_id_organisation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site'))
    )
    op.create_index('ix_site_org', 'site', ['organisation_id'], unique=False)
    op.create_table('job_run',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('procrastinate_job_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_job_run_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_job_run_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_run'))
    )
    op.create_index('ix_job_run_org_created', 'job_run', ['organisation_id', 'created_at'], unique=False)
    op.create_table('membership',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'general_manager', 'head_chef', 'shift_manager')", name=op.f('ck_membership_role_valid')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_membership_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_membership_site_id_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['organisation_user.user_id'], name=op.f('fk_membership_user_id_organisation_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership'))
    )
    op.create_index('uq_membership_user_org', 'membership', ['user_id'], unique=True, postgresql_where=sa.text('site_id IS NULL'))
    op.create_index('uq_membership_user_site', 'membership', ['user_id', 'site_id'], unique=True, postgresql_where=sa.text('site_id IS NOT NULL'))
    # ### end Alembic commands ###

    # Audit log is append-only (FR-SET-03): a trigger blocks UPDATE/DELETE for every role, and the
    # application role (if present) has no UPDATE/DELETE privilege.
    op.execute("""
        CREATE FUNCTION audit_event_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_event is append-only' USING ERRCODE = 'insufficient_privilege';
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER audit_event_no_update_delete BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_event
        FOR EACH STATEMENT EXECUTE FUNCTION audit_event_immutable();
    """)
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON audit_event FROM PUBLIC")
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'opspilot_app') THEN
                REVOKE UPDATE, DELETE, TRUNCATE ON audit_event FROM opspilot_app;
            END IF;
        END $$;
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_membership_user_site', table_name='membership', postgresql_where=sa.text('site_id IS NOT NULL'))
    op.drop_index('uq_membership_user_org', table_name='membership', postgresql_where=sa.text('site_id IS NULL'))
    op.drop_table('membership')
    op.drop_index('ix_job_run_org_created', table_name='job_run')
    op.drop_table('job_run')
    op.drop_index('ix_site_org', table_name='site')
    op.drop_table('site')
    op.drop_table('organisation_user')
    op.drop_table('rate_bucket')
    op.drop_table('organisation')
    op.drop_table('idempotency_record')
    op.drop_index('ix_audit_org_at', table_name='audit_event')
    op.drop_index('ix_audit_entity', table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS audit_event_immutable() CASCADE")
    op.execute("DROP TABLE IF EXISTS procrastinate_events, procrastinate_periodic_defers, procrastinate_workers, "
               "procrastinate_jobs CASCADE")
    op.execute("""
        DO $$ DECLARE r record; BEGIN
            FOR r IN SELECT p.oid::regprocedure AS sig FROM pg_proc p
                     JOIN pg_namespace n ON n.oid = p.pronamespace
                     WHERE n.nspname = 'public' AND p.proname LIKE 'procrastinate%' LOOP
                EXECUTE 'DROP FUNCTION IF EXISTS ' || r.sig || ' CASCADE';
            END LOOP;
            FOR r IN SELECT t.typname FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                     WHERE n.nspname = 'public' AND t.typname LIKE 'procrastinate%' AND t.typtype IN ('e', 'c') LOOP
                EXECUTE 'DROP TYPE IF EXISTS ' || quote_ident(r.typname) || ' CASCADE';
            END LOOP;
        END $$;
    """)
