"""tenancy catalogue and operations

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 10:17:41.545468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ORG = "NULLIF(current_setting('app.org_id', true), '')::uuid"
BYPASS = "current_setting('app.bypass_rls', true) = 'on'"
RLS_TABLES = ['cash_up', 'external_ref', 'goods_receipt', 'goods_receipt_line', 'ingredient', 'integration_connection', 'job_run', 'line_alias', 'membership', 'menu_item', 'menu_item_price', 'organisation_user', 'price_observation', 'purchase_order', 'purchase_order_line', 'recipe', 'recipe_line', 'sales_order', 'sales_order_line', 'shift', 'site', 'site_clock', 'site_ingredient', 'stock_count', 'stock_count_line', 'stock_movement', 'supplier', 'supplier_alias', 'supplier_product', 'unit_conversion', 'waste_entry', 'weather_day']


def rls_statements(table: str) -> list[str]:
    return [
        f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
        f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY",
        f"DROP POLICY IF EXISTS tenant_isolation ON {table}",
        f"CREATE POLICY tenant_isolation ON {table} USING ({BYPASS} OR organisation_id = {ORG}) "
        f"WITH CHECK ({BYPASS} OR organisation_id = {ORG})",
    ]


def _policy(table: str, using: str, check: str) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.execute(f"CREATE POLICY tenant_isolation ON {table} USING ({BYPASS} OR {using.format(ORG=ORG)}) "
               f"WITH CHECK ({BYPASS} OR {check.format(ORG=ORG)})")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_holiday',
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_holiday'))
    )
    op.create_index('uq_bank_holiday', 'bank_holiday', ['region', 'day'], unique=True)
    op.create_table('external_ref',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_external_ref_organisation_id_organisation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_ref'))
    )
    op.create_index('ix_external_ref_entity', 'external_ref', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_external_ref_organisation_id'), 'external_ref', ['organisation_id'], unique=False)
    op.create_index('uq_external_ref_provider_id', 'external_ref', ['organisation_id', 'provider', 'entity_type', 'external_id'], unique=True)
    op.create_table('ingredient',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('base_unit', sa.String(length=8), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('storage_area', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("base_unit IN ('g', 'ml', 'each')", name=op.f('ck_ingredient_base_unit_valid')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_ingredient_organisation_id_organisation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient'))
    )
    op.create_index(op.f('ix_ingredient_organisation_id'), 'ingredient', ['organisation_id'], unique=False)
    op.create_index('uq_ingredient_org_code', 'ingredient', ['organisation_id', 'code'], unique=True)
    op.create_table('menu_item',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_menu_item_organisation_id_organisation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item'))
    )
    op.create_index(op.f('ix_menu_item_organisation_id'), 'menu_item', ['organisation_id'], unique=False)
    op.create_index('uq_menu_item_code', 'menu_item', ['organisation_id', 'code'], unique=True)
    op.create_table('supplier',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalised_name', sa.String(length=200), nullable=False),
    sa.Column('vat_number', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('delivery_weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_supplier_organisation_id_organisation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier'))
    )
    op.create_index('ix_supplier_name_trgm', 'supplier', ['normalised_name'], unique=False, postgresql_using='gin', postgresql_ops={'normalised_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_supplier_organisation_id'), 'supplier', ['organisation_id'], unique=False)
    op.create_index('ix_supplier_vat', 'supplier', ['organisation_id', 'vat_number'], unique=False)
    op.create_table('cash_up',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('expected_cash_minor', sa.BigInteger(), nullable=False),
    sa.Column('counted_cash_minor', sa.BigInteger(), nullable=False),
    sa.Column('card_total_minor', sa.BigInteger(), nullable=False),
    sa.Column('variance_minor', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_cash_up_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_cash_up_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_up'))
    )
    op.create_index(op.f('ix_cash_up_organisation_id'), 'cash_up', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_cash_up_site_id'), 'cash_up', ['site_id'], unique=False)
    op.create_index('uq_cash_up_day', 'cash_up', ['site_id', 'business_date'], unique=True)
    op.create_table('config_value',
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'site') = (site_id IS NOT NULL)", name=op.f('ck_config_value_site_scope_has_site')),
    sa.CheckConstraint("(scope = 'system') = (organisation_id IS NULL)", name=op.f('ck_config_value_system_has_no_org')),
    sa.CheckConstraint("scope IN ('system', 'organisation', 'site')", name=op.f('ck_config_value_scope_valid')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_config_value_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_config_value_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_value'))
    )
    op.create_index('uq_config_value_scope_key', 'config_value', ['scope', 'organisation_id', 'site_id', 'key'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('integration_connection',
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('secret_ref', sa.String(length=300), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('pos','accounting','ai','mail','weather','calendar','storage')", name=op.f('ck_integration_connection_kind_valid')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_integration_connection_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_integration_connection_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_connection'))
    )
    op.create_index(op.f('ix_integration_connection_organisation_id'), 'integration_connection', ['organisation_id'], unique=False)
    op.create_index('uq_integration_scope_kind', 'integration_connection', ['organisation_id', 'site_id', 'kind'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('menu_item_price',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('price_minor', sa.BigInteger(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_menu_item_price_dates_ordered')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_menu_item_price_menu_item_id_menu_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_menu_item_price_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_menu_item_price_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_price'))
    )
    op.create_index('ix_menu_item_price', 'menu_item_price', ['site_id', 'menu_item_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_menu_item_price_organisation_id'), 'menu_item_price', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_menu_item_price_site_id'), 'menu_item_price', ['site_id'], unique=False)
    op.create_table('purchase_order',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_approval', 'committed', 'sent', 'part_received', 'received', 'cancelled')", name=op.f('ck_purchase_order_status_valid')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_purchase_order_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_purchase_order_site_id_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_purchase_order_supplier_id_supplier'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order'))
    )
    op.create_index(op.f('ix_purchase_order_organisation_id'), 'purchase_order', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_site_id'), 'purchase_order', ['site_id'], unique=False)
    op.create_index('ix_purchase_order_supplier_delivery', 'purchase_order', ['site_id', 'supplier_id', 'expected_delivery_date'], unique=False)
    op.create_index('uq_purchase_order_number', 'purchase_order', ['organisation_id', 'number'], unique=True)
    op.create_table('recipe',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('yield_portions', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('yield_portions >= 1', name=op.f('ck_recipe_yield_positive')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_recipe_menu_item_id_menu_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_recipe_organisation_id_organisation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe'))
    )
    op.create_index(op.f('ix_recipe_organisation_id'), 'recipe', ['organisation_id'], unique=False)
    op.create_index('uq_recipe_open_version', 'recipe', ['menu_item_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL'))
    op.create_index('uq_recipe_version', 'recipe', ['menu_item_id', 'version'], unique=True)
    op.create_table('sales_order',
    sa.Column('external_order_id', sa.String(length=80), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daypart', sa.String(length=16), nullable=False),
    sa.Column('covers', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('discount_minor', sa.BigInteger(), nullable=False),
    sa.Column('void_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_minor', sa.BigInteger(), nullable=False),
    sa.Column('vat_minor', sa.BigInteger(), nullable=False),
    sa.Column('revenue_ex_vat_minor', sa.BigInteger(), nullable=False),
    sa.Column('discount_reason', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_sales_order_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_sales_order_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order'))
    )
    op.create_index(op.f('ix_sales_order_organisation_id'), 'sales_order', ['organisation_id'], unique=False)
    op.create_index('ix_sales_order_site_date', 'sales_order', ['site_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_sales_order_site_id'), 'sales_order', ['site_id'], unique=False)
    op.create_index('uq_sales_order_external', 'sales_order', ['site_id', 'external_order_id'], unique=True)
    op.create_table('shift',
    sa.Column('external_shift_id', sa.String(length=80), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('staff_ref', sa.String(length=80), nullable=False),
    sa.Column('staff_display_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('hourly_rate_minor', sa.BigInteger(), nullable=False),
    sa.Column('cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_shift_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_shift_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift'))
    )
    op.create_index(op.f('ix_shift_organisation_id'), 'shift', ['organisation_id'], unique=False)
    op.create_index('ix_shift_site_date', 'shift', ['site_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_shift_site_id'), 'shift', ['site_id'], unique=False)
    op.create_index('uq_shift_external', 'shift', ['site_id', 'external_shift_id'], unique=True)
    op.create_table('site_clock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_site_clock_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_site_clock_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_clock'))
    )
    op.create_index(op.f('ix_site_clock_organisation_id'), 'site_clock', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_site_clock_site_id'), 'site_clock', ['site_id'], unique=False)
    op.create_index('uq_site_clock_site', 'site_clock', ['site_id'], unique=True)
    op.create_table('stock_count',
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('storage_area', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('counted_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_stock_count_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_stock_count_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_count'))
    )
    op.create_index(op.f('ix_stock_count_organisation_id'), 'stock_count', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_stock_count_site_id'), 'stock_count', ['site_id'], unique=False)
    op.create_table('stock_movement',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('qty_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_minor', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("type IN ('opening', 'receipt', 'theoretical_consumption', 'waste', 'count_adjustment', 'transfer')", name=op.f('ck_stock_movement_type_valid')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_stock_movement_ingredient_id_ingredient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_stock_movement_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_stock_movement_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movement'))
    )
    op.create_index(op.f('ix_stock_movement_organisation_id'), 'stock_movement', ['organisation_id'], unique=False)
    op.create_index('ix_stock_movement_site_date', 'stock_movement', ['site_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_stock_movement_site_id'), 'stock_movement', ['site_id'], unique=False)
    op.create_index('ix_stock_movement_site_ingredient_at', 'stock_movement', ['site_id', 'ingredient_id', 'at'], unique=False)
    op.create_index('uq_stock_movement_ref', 'stock_movement', ['site_id', 'ingredient_id', 'type', 'ref_type', 'ref_id'], unique=True)
    op.create_table('supplier_alias',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_supplier_alias_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_alias_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_alias'))
    )
    op.create_index(op.f('ix_supplier_alias_organisation_id'), 'supplier_alias', ['organisation_id'], unique=False)
    op.create_index('ix_supplier_alias_trgm', 'supplier_alias', ['alias'], unique=False, postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    op.create_index('uq_supplier_alias', 'supplier_alias', ['organisation_id', 'alias'], unique=True)
    op.create_table('supplier_product',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('purchase_unit', sa.String(length=30), nullable=False),
    sa.Column('pack_size', sa.String(length=60), nullable=True),
    sa.Column('base_qty_per_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('moq_units', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('contract_price_minor', sa.Integer(), nullable=True),
    sa.Column('contract_valid_until', sa.Date(), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('base_qty_per_unit > 0', name=op.f('ck_supplier_product_base_qty_positive')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_supplier_product_ingredient_id_ingredient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_supplier_product_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_product_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_product'))
    )
    op.create_index(op.f('ix_supplier_product_organisation_id'), 'supplier_product', ['organisation_id'], unique=False)
    op.create_index('uq_supplier_product_sku', 'supplier_product', ['supplier_id', 'sku'], unique=True)
    op.create_table('unit_conversion',
    sa.Column('ingredient_id', sa.Uuid(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('factor_to_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('factor_to_base > 0', name=op.f('ck_unit_conversion_factor_positive')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_unit_conversion_ingredient_id_ingredient'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_unit_conversion_organisation_id_organisation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_conversion'))
    )
    op.create_index(op.f('ix_unit_conversion_organisation_id'), 'unit_conversion', ['organisation_id'], unique=False)
    op.create_index('uq_unit_conversion', 'unit_conversion', ['organisation_id', 'ingredient_id', 'unit'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('waste_entry',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('qty_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("reason IN ('spoilage', 'prep', 'over_production', 'returned', 'staff_meal')", name=op.f('ck_waste_entry_reason_valid')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_waste_entry_ingredient_id_ingredient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_waste_entry_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_waste_entry_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_entry'))
    )
    op.create_index(op.f('ix_waste_entry_organisation_id'), 'waste_entry', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_waste_entry_site_id'), 'waste_entry', ['site_id'], unique=False)
    op.create_table('weather_day',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('temp_max_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temp_min_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('precipitation_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_weather_day_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_weather_day_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_day'))
    )
    op.create_index(op.f('ix_weather_day_organisation_id'), 'weather_day', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_weather_day_site_id'), 'weather_day', ['site_id'], unique=False)
    op.create_index('uq_weather_day', 'weather_day', ['site_id', 'day'], unique=True)
    op.create_table('goods_receipt',
    sa.Column('purchase_order_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('received_by', sa.String(length=120), nullable=False),
    sa.Column('delivery_note_ref', sa.String(length=80), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_goods_receipt_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_goods_receipt_purchase_order_id_purchase_order'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_goods_receipt_site_id_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_goods_receipt_supplier_id_supplier'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt'))
    )
    op.create_index(op.f('ix_goods_receipt_organisation_id'), 'goods_receipt', ['organisation_id'], unique=False)
    op.create_index('ix_goods_receipt_po', 'goods_receipt', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_site_id'), 'goods_receipt', ['site_id'], unique=False)
    op.create_table('line_alias',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('normalised_text', sa.String(length=300), nullable=False),
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_line_alias_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_line_alias_supplier_id_supplier'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_product.id'], name=op.f('fk_line_alias_supplier_product_id_supplier_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_alias'))
    )
    op.create_index(op.f('ix_line_alias_organisation_id'), 'line_alias', ['organisation_id'], unique=False)
    op.create_index('uq_line_alias', 'line_alias', ['supplier_id', 'normalised_text'], unique=True)
    op.create_table('price_observation',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('price_per_base_minor', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("source IN ('invoice', 'price_list', 'purchase_order', 'seed')", name=op.f('ck_price_observation_source_valid')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_price_observation_ingredient_id_ingredient'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_price_observation_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_price_observation_site_id_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_price_observation_supplier_id_supplier'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_product.id'], name=op.f('fk_price_observation_supplier_product_id_supplier_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_observation'))
    )
    op.create_index('ix_price_obs_ingredient_day', 'price_observation', ['site_id', 'ingredient_id', 'observed_on'], unique=False)
    op.create_index('ix_price_obs_product_day', 'price_observation', ['supplier_product_id', 'observed_on'], unique=False)
    op.create_index(op.f('ix_price_observation_organisation_id'), 'price_observation', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_price_observation_site_id'), 'price_observation', ['site_id'], unique=False)
    op.create_index('uq_price_obs_source', 'price_observation', ['site_id', 'supplier_product_id', 'source', 'source_ref'], unique=True)
    op.create_table('purchase_order_line',
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('qty_units', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('line_total_minor', sa.BigInteger(), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_purchase_order_line_ingredient_id_ingredient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_purchase_order_line_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_purchase_order_line_purchase_order_id_purchase_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_purchase_order_line_site_id_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_product.id'], name=op.f('fk_purchase_order_line_supplier_product_id_supplier_product'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_line'))
    )
    op.create_index(op.f('ix_purchase_order_line_organisation_id'), 'purchase_order_line', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_line_purchase_order_id'), 'purchase_order_line', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_line_site_id'), 'purchase_order_line', ['site_id'], unique=False)
    op.create_table('recipe_line',
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('waste_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('qty_base_per_portion', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_recipe_line_ingredient_id_ingredient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_recipe_line_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_line_recipe_id_recipe'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_line'))
    )
    op.create_index(op.f('ix_recipe_line_organisation_id'), 'recipe_line', ['organisation_id'], unique=False)
    op.create_index('ix_recipe_line_recipe', 'recipe_line', ['recipe_id'], unique=False)
    op.create_table('sales_order_line',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daypart', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('void_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('void_reason', sa.String(length=60), nullable=True),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('discount_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_minor', sa.BigInteger(), nullable=False),
    sa.Column('revenue_ex_vat_minor', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_sales_order_line_menu_item_id_menu_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], name=op.f('fk_sales_order_line_order_id_sales_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_sales_order_line_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_sales_order_line_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order_line'))
    )
    op.create_index('ix_sales_line_order', 'sales_order_line', ['order_id'], unique=False)
    op.create_index('ix_sales_line_site_date_item', 'sales_order_line', ['site_id', 'business_date', 'menu_item_id'], unique=False)
    op.create_index(op.f('ix_sales_order_line_organisation_id'), 'sales_order_line', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_sales_order_line_site_id'), 'sales_order_line', ['site_id'], unique=False)
    op.create_table('site_ingredient',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('par_level_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('default_supplier_product_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['default_supplier_product_id'], ['supplier_product.id'], name=op.f('fk_site_ingredient_default_supplier_product_id_supplier_product'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_site_ingredient_ingredient_id_ingredient'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_site_ingredient_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_site_ingredient_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_ingredient'))
    )
    op.create_index(op.f('ix_site_ingredient_organisation_id'), 'site_ingredient', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_site_ingredient_site_id'), 'site_ingredient', ['site_id'], unique=False)
    op.create_index('uq_site_ingredient', 'site_ingredient', ['site_id', 'ingredient_id'], unique=True)
    op.create_table('stock_count_line',
    sa.Column('count_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('counted_qty_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ledger_qty_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adjustment_qty_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['stock_count.id'], name=op.f('fk_stock_count_line_count_id_stock_count'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_stock_count_line_ingredient_id_ingredient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_stock_count_line_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_stock_count_line_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_count_line'))
    )
    op.create_index(op.f('ix_stock_count_line_organisation_id'), 'stock_count_line', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_stock_count_line_site_id'), 'stock_count_line', ['site_id'], unique=False)
    op.create_index('uq_stock_count_line', 'stock_count_line', ['count_id', 'ingredient_id'], unique=True)
    op.create_table('goods_receipt_line',
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('qty_units', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], name=op.f('fk_goods_receipt_line_goods_receipt_id_goods_receipt'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_goods_receipt_line_ingredient_id_ingredient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_goods_receipt_line_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], name=op.f('fk_goods_receipt_line_purchase_order_line_id_purchase_order_line'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_goods_receipt_line_site_id_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_product.id'], name=op.f('fk_goods_receipt_line_supplier_product_id_supplier_product'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_line'))
    )
    op.create_index(op.f('ix_goods_receipt_line_goods_receipt_id'), 'goods_receipt_line', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_line_organisation_id'), 'goods_receipt_line', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_line_site_id'), 'goods_receipt_line', ['site_id'], unique=False)
    op.create_index(op.f('ix_job_run_organisation_id'), 'job_run', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_membership_organisation_id'), 'membership', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_organisation_user_organisation_id'), 'organisation_user', ['organisation_id'], unique=False)
    op.drop_index(op.f('ix_site_org'), table_name='site')
    op.create_index(op.f('ix_site_organisation_id'), 'site', ['organisation_id'], unique=False)
    op.drop_constraint(op.f('fk_site_organisation_id_organisation'), 'site', type_='foreignkey')
    op.create_foreign_key(op.f('fk_site_organisation_id_organisation'), 'site', 'organisation', ['organisation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # ---- Tenant isolation: forced row-level security (FR-TEN-05, defence in depth) ----------------
    for table in RLS_TABLES:
        for stmt in rls_statements(table):
            op.execute(stmt)
    _policy("organisation", "id = {ORG}", "id = {ORG}")
    _policy("config_value", "organisation_id IS NULL OR organisation_id = {ORG}", "organisation_id = {ORG}")
    _policy("audit_event", "organisation_id = {ORG}", "organisation_id IS NULL OR organisation_id = {ORG}")

    # ---- Ledgers, not balances: the stock ledger is append-only (FR-STK-02) ------------------------
    op.execute("""
        CREATE FUNCTION stock_movement_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'stock_movement is append-only' USING ERRCODE = 'insufficient_privilege';
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER stock_movement_no_update_delete BEFORE UPDATE OR DELETE ON stock_movement
        FOR EACH ROW EXECUTE FUNCTION stock_movement_immutable();
    """)

    # ---- Least-privilege application role -------------------------------------------------------
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'opspilot_app') THEN
                GRANT USAGE ON SCHEMA public TO opspilot_app;
                GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO opspilot_app;
                GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO opspilot_app;
                REVOKE UPDATE, DELETE, TRUNCATE ON audit_event, stock_movement FROM opspilot_app;
                ALTER DEFAULT PRIVILEGES IN SCHEMA public
                    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO opspilot_app;
                ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO opspilot_app;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS stock_movement_immutable() CASCADE")
    for table in ("organisation", "config_value", "audit_event", "site", "membership", "organisation_user", "job_run"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_site_organisation_id_organisation'), 'site', type_='foreignkey')
    op.create_foreign_key(op.f('fk_site_organisation_id_organisation'), 'site', 'organisation', ['organisation_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_site_organisation_id'), table_name='site')
    op.create_index(op.f('ix_site_org'), 'site', ['organisation_id'], unique=False)
    op.drop_index(op.f('ix_organisation_user_organisation_id'), table_name='organisation_user')
    op.drop_index(op.f('ix_membership_organisation_id'), table_name='membership')
    op.drop_index(op.f('ix_job_run_organisation_id'), table_name='job_run')
    op.drop_index(op.f('ix_goods_receipt_line_site_id'), table_name='goods_receipt_line')
    op.drop_index(op.f('ix_goods_receipt_line_organisation_id'), table_name='goods_receipt_line')
    op.drop_index(op.f('ix_goods_receipt_line_goods_receipt_id'), table_name='goods_receipt_line')
    op.drop_table('goods_receipt_line')
    op.drop_index('uq_stock_count_line', table_name='stock_count_line')
    op.drop_index(op.f('ix_stock_count_line_site_id'), table_name='stock_count_line')
    op.drop_index(op.f('ix_stock_count_line_organisation_id'), table_name='stock_count_line')
    op.drop_table('stock_count_line')
    op.drop_index('uq_site_ingredient', table_name='site_ingredient')
    op.drop_index(op.f('ix_site_ingredient_site_id'), table_name='site_ingredient')
    op.drop_index(op.f('ix_site_ingredient_organisation_id'), table_name='site_ingredient')
    op.drop_table('site_ingredient')
    op.drop_index(op.f('ix_sales_order_line_site_id'), table_name='sales_order_line')
    op.drop_index(op.f('ix_sales_order_line_organisation_id'), table_name='sales_order_line')
    op.drop_index('ix_sales_line_site_date_item', table_name='sales_order_line')
    op.drop_index('ix_sales_line_order', table_name='sales_order_line')
    op.drop_table('sales_order_line')
    op.drop_index('ix_recipe_line_recipe', table_name='recipe_line')
    op.drop_index(op.f('ix_recipe_line_organisation_id'), table_name='recipe_line')
    op.drop_table('recipe_line')
    op.drop_index(op.f('ix_purchase_order_line_site_id'), table_name='purchase_order_line')
    op.drop_index(op.f('ix_purchase_order_line_purchase_order_id'), table_name='purchase_order_line')
    op.drop_index(op.f('ix_purchase_order_line_organisation_id'), table_name='purchase_order_line')
    op.drop_table('purchase_order_line')
    op.drop_index('uq_price_obs_source', table_name='price_observation')
    op.drop_index(op.f('ix_price_observation_site_id'), table_name='price_observation')
    op.drop_index(op.f('ix_price_observation_organisation_id'), table_name='price_observation')
    op.drop_index('ix_price_obs_product_day', table_name='price_observation')
    op.drop_index('ix_price_obs_ingredient_day', table_name='price_observation')
    op.drop_table('price_observation')
    op.drop_index('uq_line_alias', table_name='line_alias')
    op.drop_index(op.f('ix_line_alias_organisation_id'), table_name='line_alias')
    op.drop_table('line_alias')
    op.drop_index(op.f('ix_goods_receipt_site_id'), table_name='goods_receipt')
    op.drop_index('ix_goods_receipt_po', table_name='goods_receipt')
    op.drop_index(op.f('ix_goods_receipt_organisation_id'), table_name='goods_receipt')
    op.drop_table('goods_receipt')
    op.drop_index('uq_weather_day', table_name='weather_day')
    op.drop_index(op.f('ix_weather_day_site_id'), table_name='weather_day')
    op.drop_index(op.f('ix_weather_day_organisation_id'), table_name='weather_day')
    op.drop_table('weather_day')
    op.drop_index(op.f('ix_waste_entry_site_id'), table_name='waste_entry')
    op.drop_index(op.f('ix_waste_entry_organisation_id'), table_name='waste_entry')
    op.drop_table('waste_entry')
    op.drop_index('uq_unit_conversion', table_name='unit_conversion', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_unit_conversion_organisation_id'), table_name='unit_conversion')
    op.drop_table('unit_conversion')
    op.drop_index('uq_supplier_product_sku', table_name='supplier_product')
    op.drop_index(op.f('ix_supplier_product_organisation_id'), table_name='supplier_product')
    op.drop_table('supplier_product')
    op.drop_index('uq_supplier_alias', table_name='supplier_alias')
    op.drop_index('ix_supplier_alias_trgm', table_name='supplier_alias', postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_supplier_alias_organisation_id'), table_name='supplier_alias')
    op.drop_table('supplier_alias')
    op.drop_index('uq_stock_movement_ref', table_name='stock_movement')
    op.drop_index('ix_stock_movement_site_ingredient_at', table_name='stock_movement')
    op.drop_index(op.f('ix_stock_movement_site_id'), table_name='stock_movement')
    op.drop_index('ix_stock_movement_site_date', table_name='stock_movement')
    op.drop_index(op.f('ix_stock_movement_organisation_id'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index(op.f('ix_stock_count_site_id'), table_name='stock_count')
    op.drop_index(op.f('ix_stock_count_organisation_id'), table_name='stock_count')
    op.drop_table('stock_count')
    op.drop_index('uq_site_clock_site', table_name='site_clock')
    op.drop_index(op.f('ix_site_clock_site_id'), table_name='site_clock')
    op.drop_index(op.f('ix_site_clock_organisation_id'), table_name='site_clock')
    op.drop_table('site_clock')
    op.drop_index('uq_shift_external', table_name='shift')
    op.drop_index(op.f('ix_shift_site_id'), table_name='shift')
    op.drop_index('ix_shift_site_date', table_name='shift')
    op.drop_index(op.f('ix_shift_organisation_id'), table_name='shift')
    op.drop_table('shift')
    op.drop_index('uq_sales_order_external', table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_site_id'), table_name='sales_order')
    op.drop_index('ix_sales_order_site_date', table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_organisation_id'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_index('uq_recipe_version', table_name='recipe')
    op.drop_index('uq_recipe_open_version', table_name='recipe', postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_index(op.f('ix_recipe_organisation_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index('uq_purchase_order_number', table_name='purchase_order')
    op.drop_index('ix_purchase_order_supplier_delivery', table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_site_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_organisation_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_menu_item_price_site_id'), table_name='menu_item_price')
    op.drop_index(op.f('ix_menu_item_price_organisation_id'), table_name='menu_item_price')
    op.drop_index('ix_menu_item_price', table_name='menu_item_price')
    op.drop_table('menu_item_price')
    op.drop_index('uq_integration_scope_kind', table_name='integration_connection', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_integration_connection_organisation_id'), table_name='integration_connection')
    op.drop_table('integration_connection')
    op.drop_index('uq_config_value_scope_key', table_name='config_value', postgresql_nulls_not_distinct=True)
    op.drop_table('config_value')
    op.drop_index('uq_cash_up_day', table_name='cash_up')
    op.drop_index(op.f('ix_cash_up_site_id'), table_name='cash_up')
    op.drop_index(op.f('ix_cash_up_organisation_id'), table_name='cash_up')
    op.drop_table('cash_up')
    op.drop_index('ix_supplier_vat', table_name='supplier')
    op.drop_index(op.f('ix_supplier_organisation_id'), table_name='supplier')
    op.drop_index('ix_supplier_name_trgm', table_name='supplier', postgresql_using='gin', postgresql_ops={'normalised_name': 'gin_trgm_ops'})
    op.drop_table('supplier')
    op.drop_index('uq_menu_item_code', table_name='menu_item')
    op.drop_index(op.f('ix_menu_item_organisation_id'), table_name='menu_item')
    op.drop_table('menu_item')
    op.drop_index('uq_ingredient_org_code', table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_organisation_id'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index('uq_external_ref_provider_id', table_name='external_ref')
    op.drop_index(op.f('ix_external_ref_organisation_id'), table_name='external_ref')
    op.drop_index('ix_external_ref_entity', table_name='external_ref')
    op.drop_table('external_ref')
    op.drop_index('uq_bank_holiday', table_name='bank_holiday')
    op.drop_table('bank_holiday')
    # ### end Alembic commands ###
