"""invoice intake

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 11:29:37.269038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ORG = "NULLIF(current_setting('app.org_id', true), '')::uuid"
BYPASS = "current_setting('app.bypass_rls', true) = 'on'"
RLS_TABLES = ['ai_call', 'invoice', 'invoice_document', 'invoice_exception', 'invoice_line', 'invoice_transition']


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_document',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=True),
    sa.Column('preview_key', sa.String(length=400), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('doc_type', sa.String(length=24), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('multiple_documents', sa.Boolean(), nullable=True),
    sa.Column('classification_reason', sa.String(length=300), nullable=True),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=600), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("state IN ('received', 'classifying', 'extracting', 'validating', 'matching', 'needs_review', 'ready_for_approval', 'approved', 'rejected', 'posted', 'not_invoice', 'duplicate', 'failed')", name=op.f('ck_invoice_document_state_valid')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_invoice_document_confidence_range')),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['invoice_document.id'], name=op.f('fk_invoice_document_duplicate_of_id_invoice_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_invoice_document_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_invoice_document_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_document'))
    )
    op.create_index(op.f('ix_invoice_document_organisation_id'), 'invoice_document', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_invoice_document_site_id'), 'invoice_document', ['site_id'], unique=False)
    op.create_index('ix_invoice_document_site_state', 'invoice_document', ['site_id', 'state', 'created_at'], unique=False)
    op.create_index('uq_invoice_document_sha', 'invoice_document', ['site_id', 'sha256'], unique=True, postgresql_where=sa.text("duplicate_of_id IS NULL AND state <> 'failed'"))
    op.create_table('ai_call',
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.String(length=400), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['invoice_document.id'], name=op.f('fk_ai_call_document_id_invoice_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_ai_call_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_ai_call_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_call'))
    )
    op.create_index(op.f('ix_ai_call_organisation_id'), 'ai_call', ['organisation_id'], unique=False)
    op.create_index('ix_ai_call_site_at', 'ai_call', ['site_id', 'at'], unique=False)
    op.create_index(op.f('ix_ai_call_site_id'), 'ai_call', ['site_id'], unique=False)
    op.create_table('invoice_transition',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=True),
    sa.Column('to_state', sa.String(length=24), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=600), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['invoice_document.id'], name=op.f('fk_invoice_transition_document_id_invoice_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_invoice_transition_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_invoice_transition_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_transition'))
    )
    op.create_index('ix_invoice_transition_doc', 'invoice_transition', ['document_id', 'at'], unique=False)
    op.create_index(op.f('ix_invoice_transition_organisation_id'), 'invoice_transition', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_invoice_transition_site_id'), 'invoice_transition', ['site_id'], unique=False)
    op.create_table('invoice',
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_name', sa.String(length=300), nullable=True),
    sa.Column('supplier_vat_number', sa.String(length=60), nullable=True),
    sa.Column('supplier_address', sa.String(length=400), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('normalised_number', sa.String(length=80), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('po_reference', sa.String(length=80), nullable=True),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=True),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subtotal_minor', sa.BigInteger(), nullable=False),
    sa.Column('vat_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('ai_subtotal_minor', sa.BigInteger(), nullable=True),
    sa.Column('ai_vat_minor', sa.BigInteger(), nullable=True),
    sa.Column('ai_total_minor', sa.BigInteger(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_role', sa.String(length=32), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.String(length=600), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['invoice_document.id'], name=op.f('fk_invoice_document_id_invoice_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], name=op.f('fk_invoice_goods_receipt_id_goods_receipt'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_invoice_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_invoice_purchase_order_id_purchase_order'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_invoice_site_id_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_invoice_supplier_id_supplier'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice'))
    )
    op.create_index(op.f('ix_invoice_organisation_id'), 'invoice', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_invoice_site_id'), 'invoice', ['site_id'], unique=False)
    op.create_index('ix_invoice_supplier_date', 'invoice', ['site_id', 'supplier_id', 'invoice_date'], unique=False)
    op.create_index('ix_invoice_supplier_number', 'invoice', ['site_id', 'supplier_id', 'normalised_number'], unique=False)
    op.create_index('uq_invoice_document', 'invoice', ['document_id'], unique=True, postgresql_where=sa.text('document_id IS NOT NULL'))
    op.create_table('invoice_line',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('raw_description', sa.String(length=400), nullable=False),
    sa.Column('supplier_sku', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('uom', sa.String(length=30), nullable=True),
    sa.Column('pack_size', sa.String(length=60), nullable=True),
    sa.Column('unit_price_minor', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('line_total_minor', sa.BigInteger(), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('supplier_product_id', sa.Uuid(), nullable=True),
    sa.Column('ingredient_id', sa.Uuid(), nullable=True),
    sa.Column('qty_base', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_per_base_minor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('match_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('non_stock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_invoice_line_ingredient_id_ingredient'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_line_invoice_id_invoice'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_invoice_line_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_invoice_line_site_id_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_product.id'], name=op.f('fk_invoice_line_supplier_product_id_supplier_product'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line'))
    )
    op.create_index(op.f('ix_invoice_line_organisation_id'), 'invoice_line', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_site_id'), 'invoice_line', ['site_id'], unique=False)
    op.create_index('uq_invoice_line_no', 'invoice_line', ['invoice_id', 'line_no'], unique=True)
    op.create_table('invoice_exception',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('line_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('blocks_approval', sa.Boolean(), nullable=False),
    sa.Column('requires_role', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=600), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('accepted_by', sa.String(length=120), nullable=True),
    sa.Column('accepted_note', sa.String(length=600), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("code IN ('math_error', 'missing_field', 'unmatched_unit', 'unknown_supplier', 'unmatched_line', 'price_increase', 'contract_breach', 'qty_mismatch', 'price_mismatch', 'possible_duplicate', 'low_confidence')", name=op.f('ck_invoice_exception_code_valid')),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_invoice_exception_severity_valid')),
    sa.CheckConstraint("status IN ('open', 'accepted', 'resolved')", name=op.f('ck_invoice_exception_status_valid')),
    sa.ForeignKeyConstraint(['document_id'], ['invoice_document.id'], name=op.f('fk_invoice_exception_document_id_invoice_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_exception_invoice_id_invoice'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_id'], ['invoice_line.id'], name=op.f('fk_invoice_exception_line_id_invoice_line'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_invoice_exception_organisation_id_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_invoice_exception_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_exception'))
    )
    op.create_index('ix_invoice_exception_doc', 'invoice_exception', ['document_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoice_exception_organisation_id'), 'invoice_exception', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_invoice_exception_site_id'), 'invoice_exception', ['site_id'], unique=False)
    op.add_column('goods_receipt', sa.Column('invoice_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###

    # Tenant isolation (FR-TEN-05) for the new tables; grants for the application role.
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY tenant_isolation ON {table} USING ({BYPASS} OR organisation_id = {ORG}) "
                   f"WITH CHECK ({BYPASS} OR organisation_id = {ORG})")
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'opspilot_app') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO opspilot_app;
                REVOKE UPDATE, DELETE, TRUNCATE ON audit_event, stock_movement FROM opspilot_app;
                REVOKE UPDATE, DELETE ON invoice_transition, ai_call FROM opspilot_app;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods_receipt', 'invoice_id')
    op.drop_index(op.f('ix_invoice_exception_site_id'), table_name='invoice_exception')
    op.drop_index(op.f('ix_invoice_exception_organisation_id'), table_name='invoice_exception')
    op.drop_index('ix_invoice_exception_doc', table_name='invoice_exception')
    op.drop_table('invoice_exception')
    op.drop_index('uq_invoice_line_no', table_name='invoice_line')
    op.drop_index(op.f('ix_invoice_line_site_id'), table_name='invoice_line')
    op.drop_index(op.f('ix_invoice_line_organisation_id'), table_name='invoice_line')
    op.drop_table('invoice_line')
    op.drop_index('uq_invoice_document', table_name='invoice', postgresql_where=sa.text('document_id IS NOT NULL'))
    op.drop_index('ix_invoice_supplier_number', table_name='invoice')
    op.drop_index('ix_invoice_supplier_date', table_name='invoice')
    op.drop_index(op.f('ix_invoice_site_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_organisation_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_invoice_transition_site_id'), table_name='invoice_transition')
    op.drop_index(op.f('ix_invoice_transition_organisation_id'), table_name='invoice_transition')
    op.drop_index('ix_invoice_transition_doc', table_name='invoice_transition')
    op.drop_table('invoice_transition')
    op.drop_index(op.f('ix_ai_call_site_id'), table_name='ai_call')
    op.drop_index('ix_ai_call_site_at', table_name='ai_call')
    op.drop_index(op.f('ix_ai_call_organisation_id'), table_name='ai_call')
    op.drop_table('ai_call')
    op.drop_index('uq_invoice_document_sha', table_name='invoice_document', postgresql_where=sa.text("duplicate_of_id IS NULL AND state <> 'failed'"))
    op.drop_index('ix_invoice_document_site_state', table_name='invoice_document')
    op.drop_index(op.f('ix_invoice_document_site_id'), table_name='invoice_document')
    op.drop_index(op.f('ix_invoice_document_organisation_id'), table_name='invoice_document')
    op.drop_table('invoice_document')
    # ### end Alembic commands ###
